version: '3.1'

services:
  postgres:
    image: 'postgres:10.7'
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    # healthcheck:
    #   test: ['CMD-SHELL', 'pg_isready -U automated-floating-service']
    #   interval: 30s
    #   timeout: 30s
    #   retries: 3