// Code generated by MockGen. DO NOT EDIT.
// Source: ./usecase/repository/repository.go
//
// Generated by this command:
//
//	mockgen -source=./usecase/repository/repository.go -destination=./mock/repository/repository.go -package=mock_repository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	domain "github.com/nobbyphala/Brick/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockDisbursement is a mock of Disbursement interface.
type MockDisbursement struct {
	ctrl     *gomock.Controller
	recorder *MockDisbursementMockRecorder
}

// MockDisbursementMockRecorder is the mock recorder for MockDisbursement.
type MockDisbursementMockRecorder struct {
	mock *MockDisbursement
}

// NewMockDisbursement creates a new mock instance.
func NewMockDisbursement(ctrl *gomock.Controller) *MockDisbursement {
	mock := &MockDisbursement{ctrl: ctrl}
	mock.recorder = &MockDisbursementMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDisbursement) EXPECT() *MockDisbursementMockRecorder {
	return m.recorder
}

// GetByTransactionId mocks base method.
func (m *MockDisbursement) GetByTransactionId(ctx context.Context, bankTransactionId string) (*domain.Disbursement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTransactionId", ctx, bankTransactionId)
	ret0, _ := ret[0].(*domain.Disbursement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTransactionId indicates an expected call of GetByTransactionId.
func (mr *MockDisbursementMockRecorder) GetByTransactionId(ctx, bankTransactionId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTransactionId", reflect.TypeOf((*MockDisbursement)(nil).GetByTransactionId), ctx, bankTransactionId)
}

// Insert mocks base method.
func (m *MockDisbursement) Insert(ctx context.Context, disbursement domain.Disbursement) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, disbursement)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockDisbursementMockRecorder) Insert(ctx, disbursement any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockDisbursement)(nil).Insert), ctx, disbursement)
}

// UpdateById mocks base method.
func (m *MockDisbursement) UpdateById(ctx context.Context, id string, updatedData domain.Disbursement) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateById", ctx, id, updatedData)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateById indicates an expected call of UpdateById.
func (mr *MockDisbursementMockRecorder) UpdateById(ctx, id, updatedData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateById", reflect.TypeOf((*MockDisbursement)(nil).UpdateById), ctx, id, updatedData)
}
